### ISSUE TITLE
review request

### ISSUE THREAD

**Issue by Reggeditt** [deniodev/Catalog#24]
https://github.com/deniodev/Catalog/projects/1

we are a group of three (3)

Team member #1: @deniodev 
Team member #2: @Reggeditt 
Team member #3: @fezzopro

**Comment by iambenkis** [comment]
## Hi Team, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
- [ ] Kindly add a description to this task https://github.com/deniodev/Catalog/issues/6
- [ ] Kindly provide a description to this task https://github.com/deniodev/Catalog/issues/13
- [ ] Kindly provide a description to this task  https://github.com/deniodev/Catalog/issues/20 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zainsadaqat** [comment]
# Pull Request Approved ✅ 🎊 🎉 
## Hello Team! 👋 

### Things to appreciate
- [ ] Good job for implementing the things requested by the previous code reviewer.

### Your project is complete!  There is nothing else to say other than it's time to merge it.

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 ☑️ 

<img src="https://media1.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
